# Generated by Django 5.1 on 2024-09-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friendlist_friends_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='pending',
            new_name='is_pending',
        ),
    ]
